export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const NULIFY_AUTH_STATE = 'NULIFY_AUTH_STATE';
export const SIGN_IN_URL = '/login';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';
export const GET_USER_LIST_URL = '/users?page=';

export const GET_SIGLE_USER = 'GET_SIGLE_USER';
export const GET_SIGLE_USER_SUCCESS = 'GET_SIGLE_USER_SUCCESS';
export const GET_SIGLE_USER_FAILURE = 'GET_SIGLE_USER_FAILURE';
export const GET_SIGLE_USER_URL = '/users/';

export const AUTH_CHECKOUT_SUCCESS = 'AUTH_CHECKOUT_SUCCESS';
export const AUTH_CHECKOUT_FAILURE = 'AUTH_CHECKOUT_FAILURE';
